package com.trm.cryptosphere.domain.model

import kotlinx.serialization.Serializable

@Serializable
data class TokenInfo(
  val id: Int,
  val name: String,
  val symbol: String,
  val category: String?,
  val description: String?,
  val slug: String?,
  val logo: String?,
  val subreddit: String?,
  val notice: String?,
  val tags: List<String>?,
  val tagNames: List<String>?,
  val tagGroups: List<String>?,
  val urls: TokenUrls?,
  val platform: TokenPlatform?,
  val dateAdded: String?,
  val twitterUsername: String?,
  val dateLaunched: String?,
  val selfReportedCirculatingSupply: Double?,
  val selfReportedTags: List<String>?,
  val selfReportedMarketCap: Double?,
  val infiniteSupply: Boolean?,
)

fun mockTokenInfoList(): List<TokenInfo> =
  listOf(
    TokenInfo(
      id = 1,
      name = "Bitcoin",
      symbol = "BTC",
      category = "coin",
      description =
        "Bitcoin (BTC) is a cryptocurrency launched in 2010. Users are able to generate BTC through the process of mining. Bitcoin has a current supply of 19,891,696. The last known price of Bitcoin is 117,846.43492418 USD and is down -0.19 over the last 24 hours. It is currently trading on 12253 active market(s) with $42,497,165,433.17 traded over the last 24 hours. More information can be found at https://bitcoin.org/.",
      slug = "bitcoin",
      logo = "https://s2.coinmarketcap.com/static/img/coins/64x64/1.png",
      subreddit = "bitcoin",
      notice = "",
      tags =
        listOf(
          "mineable",
          "pow",
          "sha-256",
          "store-of-value",
          "state-channel",
          "coinbase-ventures-portfolio",
          "three-arrows-capital-portfolio",
          "polychain-capital-portfolio",
          "binance-labs-portfolio",
          "blockchain-capital-portfolio",
          "boostvc-portfolio",
          "cms-holdings-portfolio",
          "dcg-portfolio",
          "dragonfly-capital-portfolio",
          "electric-capital-portfolio",
          "fabric-ventures-portfolio",
          "framework-ventures-portfolio",
          "galaxy-digital-portfolio",
          "huobi-capital-portfolio",
          "alameda-research-portfolio",
          "a16z-portfolio",
          "1confirmation-portfolio",
          "winklevoss-capital-portfolio",
          "usv-portfolio",
          "placeholder-ventures-portfolio",
          "pantera-capital-portfolio",
          "multicoin-capital-portfolio",
          "paradigm-portfolio",
          "bitcoin-ecosystem",
          "layer-1",
          "ftx-bankruptcy-estate",
          "2017-2018-alt-season",
          "us-strategic-crypto-reserve",
          "binance-ecosystem",
          "binance-listing",
        ),
      tagNames =
        listOf(
          "Mineable",
          "PoW",
          "SHA-256",
          "Store Of Value",
          "State Channel",
          "Coinbase Ventures Portfolio",
          "Three Arrows Capital Portfolio",
          "Polychain Capital Portfolio",
          "YZi Labs Portfolio",
          "Blockchain Capital Portfolio",
          "BoostVC Portfolio",
          "CMS Holdings Portfolio",
          "DCG Portfolio",
          "DragonFly Capital Portfolio",
          "Electric Capital Portfolio",
          "Fabric Ventures Portfolio",
          "Framework Ventures Portfolio",
          "Galaxy Digital Portfolio",
          "Huobi Capital Portfolio",
          "Alameda Research Portfolio",
          "a16z Portfolio",
          "1Confirmation Portfolio",
          "Winklevoss Capital Portfolio",
          "USV Portfolio",
          "Placeholder Ventures Portfolio",
          "Pantera Capital Portfolio",
          "Multicoin Capital Portfolio",
          "Paradigm Portfolio",
          "Bitcoin Ecosystem",
          "Layer 1",
          "FTX Bankruptcy Estate ",
          "2017/18 Alt season",
          "US Strategic Crypto Reserve",
          "Binance Ecosystem",
          "Binance Listing",
        ),
      tagGroups =
        listOf(
          "OTHERS",
          "ALGORITHM",
          "ALGORITHM",
          "CATEGORY",
          "CATEGORY",
          "CATEGORY",
          "CATEGORY",
          "CATEGORY",
          "CATEGORY",
          "CATEGORY",
          "CATEGORY",
          "CATEGORY",
          "CATEGORY",
          "CATEGORY",
          "CATEGORY",
          "CATEGORY",
          "CATEGORY",
          "CATEGORY",
          "CATEGORY",
          "CATEGORY",
          "CATEGORY",
          "CATEGORY",
          "CATEGORY",
          "CATEGORY",
          "CATEGORY",
          "CATEGORY",
          "CATEGORY",
          "CATEGORY",
          "PLATFORM",
          "CATEGORY",
          "CATEGORY",
          "CATEGORY",
          "CATEGORY",
          "CATEGORY",
          "CATEGORY",
        ),
      urls =
        TokenUrls(
          website = listOf("https://bitcoin.org/"),
          twitter = emptyList(),
          messageBoard = listOf("https://bitcointalk.org"),
          chat = emptyList(),
          facebook = emptyList(),
          explorer =
            listOf(
              "https://blockchain.info/",
              "https://live.blockcypher.com/btc/",
              "https://blockchair.com/bitcoin",
              "https://explorer.viabtc.com/btc",
              "https://www.okx.com/web3/explorer/btc",
            ),
          reddit = listOf("https://reddit.com/r/bitcoin"),
          technicalDoc = listOf("https://bitcoin.org/bitcoin.pdf"),
          sourceCode = listOf("https://github.com/bitcoin/bitcoin"),
          announcement = emptyList(),
        ),
      platform = null,
      dateAdded = "2010-07-13T00:00:00.000Z",
      twitterUsername = "",
      dateLaunched = "2010-07-13T00:00:00.000Z",
      selfReportedCirculatingSupply = null,
      selfReportedTags = null,
      selfReportedMarketCap = null,
      infiniteSupply = false,
    ),
    TokenInfo(
      id = 2,
      name = "Litecoin",
      symbol = "LTC",
      category = "coin",
      description =
        "Litecoin (LTC) is a cryptocurrency . Users are able to generate LTC through the process of mining. Litecoin has a current supply of 84,000,000 with 76,069,014.48347135 in circulation. The last known price of Litecoin is 94.45763733 USD and is up 1.11 over the last 24 hours. It is currently trading on 1385 active market(s) with $436,579,423.64 traded over the last 24 hours. More information can be found at https://litecoin.org/.",
      slug = "litecoin",
      logo = "https://s2.coinmarketcap.com/static/img/coins/64x64/2.png",
      subreddit = "litecoin",
      notice = "",
      tags =
        listOf(
          "mineable",
          "pow",
          "scrypt",
          "medium-of-exchange",
          "layer-1",
          "2017-2018-alt-season",
          "made-in-america",
          "binance-ecosystem",
          "binance-listing",
        ),
      tagNames =
        listOf(
          "Mineable",
          "PoW",
          "Scrypt",
          "Medium of Exchange",
          "Layer 1",
          "2017/18 Alt season",
          "Made in America",
          "Binance Ecosystem",
          "Binance Listing",
        ),
      tagGroups =
        listOf(
          "OTHERS",
          "ALGORITHM",
          "ALGORITHM",
          "INDUSTRY",
          "CATEGORY",
          "CATEGORY",
          "CATEGORY",
          "CATEGORY",
          "CATEGORY",
        ),
      urls =
        TokenUrls(
          website = listOf("https://litecoin.org/"),
          twitter = listOf("https://twitter.com/litecoin"),
          messageBoard = listOf("https://litecointalk.io/", "https://litecoin-foundation.org/"),
          chat = listOf("https://telegram.me/litecoin"),
          facebook = emptyList(),
          explorer =
            listOf(
              "https://blockchair.com/litecoin",
              "https://app.nansen.ai/token-god-mode?chain=bnb&tab=transactions&tokenAddress=0x4338665cbb7b2485a8855a139b75d5e34ab0db94",
              "https://chainz.cryptoid.info/ltc/",
              "http://explorer.litecoin.net/chain/Litecoin",
              "https://www.okx.com/web3/explorer/ltc",
            ),
          reddit = listOf("https://reddit.com/r/litecoin"),
          technicalDoc = emptyList(),
          sourceCode = listOf("https://github.com/litecoin-project/litecoin"),
          announcement = listOf("https://bitcointalk.org/index.php?topic=47417.0"),
        ),
      platform =
        TokenPlatform(
          id = 2502,
          name = "Huobi Token",
          slug = "htx-token",
          symbol = "HT",
          tokenAddress = "0xecb56cf772b5c9a6907fb7d32387da2fcbfb63b4",
        ),
      dateAdded = "2013-04-28T00:00:00.000Z",
      twitterUsername = "litecoin",
      dateLaunched = null,
      selfReportedCirculatingSupply = null,
      selfReportedTags = null,
      selfReportedMarketCap = null,
      infiniteSupply = false,
    ),
    TokenInfo(
      id = 3,
      name = "Namecoin",
      symbol = "NMC",
      category = "coin",
      description =
        "Namecoin (NMC) is a cryptocurrency . Users are able to generate NMC through the process of mining. Namecoin has a current supply of 14,736,400. The last known price of Namecoin is 1.22857614 USD and is up 1.61 over the last 24 hours. It is currently trading on 7 active market(s) with $4,656.37 traded over the last 24 hours. More information can be found at https://www.namecoin.org/.",
      slug = "namecoin",
      logo = "https://s2.coinmarketcap.com/static/img/coins/64x64/3.png",
      subreddit = "namecoin",
      notice = "",
      tags = listOf("mineable", "pow", "sha-256", "platform"),
      tagNames = listOf("Mineable", "PoW", "SHA-256", "Platform"),
      tagGroups = listOf("OTHERS", "ALGORITHM", "ALGORITHM", "CATEGORY"),
      urls =
        TokenUrls(
          website = listOf("https://www.namecoin.org/"),
          twitter = listOf("https://twitter.com/Namecoin"),
          messageBoard = emptyList(),
          chat = listOf("https://www.namecoin.org/resources/chat/"),
          facebook = emptyList(),
          explorer =
            listOf(
              "https://nmc.tokenview.com/",
              "https://www.namebrow.se/",
              "https://namecha.in/",
              "https://chainz.cryptoid.info/nmc/",
            ),
          reddit = listOf("https://reddit.com/r/namecoin"),
          technicalDoc = listOf("https://www.namecoin.org/resources/whitepaper/"),
          sourceCode = listOf("https://github.com/namecoin"),
          announcement = listOf("https://bitcointalk.org/?topic=6017.0"),
        ),
      platform = null,
      dateAdded = "2013-04-28T00:00:00.000Z",
      twitterUsername = "Namecoin",
      dateLaunched = null,
      selfReportedCirculatingSupply = null,
      selfReportedTags = null,
      selfReportedMarketCap = null,
      infiniteSupply = false,
    ),
    TokenInfo(
      id = 4,
      name = "Terracoin",
      symbol = "TRC",
      category = "coin",
      description =
        "Terracoin (TRC) is a cryptocurrency launched in 2012. Users are able to generate TRC through the process of mining. Terracoin has a current supply of 35,039,019.14956619 with 0 in circulation. The last known price of Terracoin is 0.01414195 USD and is down -0.20 over the last 24 hours. It is currently trading on 7 active market(s) with $0.00 traded over the last 24 hours. More information can be found at http://www.terracoin.io/.",
      slug = "terracoin",
      logo = "https://s2.coinmarketcap.com/static/img/coins/64x64/4.png",
      subreddit = "terracoin",
      notice = "",
      tags = listOf("mineable", "pow", "sha-256", "masternodes"),
      tagNames = listOf("Mineable", "PoW", "SHA-256", "Masternodes"),
      tagGroups = listOf("OTHERS", "ALGORITHM", "ALGORITHM", "CATEGORY"),
      urls =
        TokenUrls(
          website = listOf("http://www.terracoin.io/"),
          twitter = listOf("https://twitter.com/Terracoin_TRC"),
          messageBoard = listOf("https://medium.com/@clockuniverse"),
          chat = listOf("https://discord.gg/enjYkRmxm9", "https://t.me/terracoin"),
          facebook = listOf("https://www.facebook.com/TheTerracoinFoundation"),
          explorer =
            listOf(
              "https://insight.terracoin.io/",
              "https://explorer.terracoin.io/chain/Terracoin",
              "https://chainz.cryptoid.info/trc/",
            ),
          reddit = listOf("https://reddit.com/r/terracoin"),
          technicalDoc = listOf("https://wiki.terracoin.io/view/Whitepaper"),
          sourceCode = listOf("https://github.com/terracoin"),
          announcement = listOf("https://bitcointalk.org/index.php?topic=1364146.0"),
        ),
      platform = null,
      dateAdded = "2013-04-28T00:00:00.000Z",
      twitterUsername = "Terracoin_TRC",
      dateLaunched = "2012-10-26T00:00:00.000Z",
      selfReportedCirculatingSupply = 35038960.65,
      selfReportedTags =
        listOf(
          "Hybrid - PoW & PoS",
          "SHA-256",
          "Philanthropy",
          "Store Of Value",
          "Atomic Swaps",
          "Privacy",
          "Mixer & Coinjoin",
          "Masternodes",
          "DAO",
          "Wallet",
          "Governance",
          "Layer 1",
        ),
      selfReportedMarketCap = 495548.1410176276,
      infiniteSupply = false,
    ),
    TokenInfo(
      id = 5,
      name = "Peercoin",
      symbol = "PPC",
      category = "coin",
      description =
        "Peercoin (PPC) is a cryptocurrency . Users are able to generate PPC through the process of mining. Peercoin has a current supply of 29,663,781.66153835. The last known price of Peercoin is 0.30738101 USD and is down -0.39 over the last 24 hours. It is currently trading on 42 active market(s) with $4,070.66 traded over the last 24 hours. More information can be found at http://www.peercoin.net.",
      slug = "peercoin",
      logo = "https://s2.coinmarketcap.com/static/img/coins/64x64/5.png",
      subreddit = "peercoin",
      notice = "",
      tags =
        listOf(
          "mineable",
          "hybrid-pow-pos",
          "sha-256",
          "medium-of-exchange",
          "store-of-value",
          "defi",
          "payments",
          "staking",
          "ethereum-ecosystem",
          "polygon-ecosystem",
          "bitcoin-ecosystem",
        ),
      tagNames =
        listOf(
          "Mineable",
          "Hybrid - PoW & PoS",
          "SHA-256",
          "Medium of Exchange",
          "Store Of Value",
          "DeFi",
          "Payments",
          "Staking",
          "Ethereum Ecosystem",
          "Polygon Ecosystem",
          "Bitcoin Ecosystem",
        ),
      tagGroups =
        listOf(
          "OTHERS",
          "ALGORITHM",
          "ALGORITHM",
          "INDUSTRY",
          "CATEGORY",
          "CATEGORY",
          "INDUSTRY",
          "CATEGORY",
          "PLATFORM",
          "PLATFORM",
          "PLATFORM",
        ),
      urls =
        TokenUrls(
          website = listOf("http://www.peercoin.net"),
          twitter = listOf("https://twitter.com/PeercoinPPC"),
          messageBoard = listOf("https://talk.peercoin.net"),
          chat = listOf("https://t.me/peercoin", "https://discord.gg/m294ReV"),
          facebook = emptyList(),
          explorer =
            listOf(
              "https://chainz.cryptoid.info/ppc/",
              "https://app.nansen.ai/token-god-mode?chain=ethereum&tab=transactions&tokenAddress=0x044d078F1c86508e13328842Cc75AC021B272958",
              "https://explorer.peercoin.net/",
              "https://etherscan.io/token/0x044d078F1c86508e13328842Cc75AC021B272958",
              "https://polygonscan.com/token/0x91E7E32C710661C44ae44D10Aa86135d91C3Ed65",
            ),
          reddit = listOf("https://reddit.com/r/peercoin"),
          technicalDoc = listOf("https://docs.peercoin.net/"),
          sourceCode = listOf("https://github.com/peercoin/peercoin"),
          announcement = listOf("https://bitcointalk.org/index.php?topic=101820.0"),
        ),
      platform =
        TokenPlatform(
          id = 1027,
          name = "Ethereum",
          slug = "ethereum",
          symbol = "ETH",
          tokenAddress = "0x044d078F1c86508e13328842Cc75AC021B272958",
        ),
      dateAdded = "2013-04-28T00:00:00.000Z",
      twitterUsername = "PeercoinPPC",
      dateLaunched = null,
      selfReportedCirculatingSupply = null,
      selfReportedTags = null,
      selfReportedMarketCap = null,
      infiniteSupply = false,
    ),
    TokenInfo(
      id = 6,
      name = "Novacoin",
      symbol = "NVC",
      category = "coin",
      description =
        "Novacoin (NVC) is a cryptocurrency launched in 2013. Users are able to generate NVC through the process of mining. Novacoin has a current supply of 4,526,390.522174 with 0 in circulation. The last known price of Novacoin is 0.02592691 USD and is down -0.20 over the last 24 hours. It is currently trading on 4 active market(s) with $2.13 traded over the last 24 hours. More information can be found at https://nova-coin.org.",
      slug = "novacoin",
      logo = "https://s2.coinmarketcap.com/static/img/coins/64x64/6.png",
      subreddit = "NovacoinCommunity/",
      notice = "",
      tags = listOf("mineable", "hybrid-pow-pos", "scrypt", "bnb-chain-ecosystem"),
      tagNames = listOf("Mineable", "Hybrid - PoW & PoS", "Scrypt", "BNB Chain Ecosystem"),
      tagGroups = listOf("OTHERS", "ALGORITHM", "ALGORITHM", "PLATFORM"),
      urls =
        TokenUrls(
          website = listOf("https://nova-coin.org", "https://novacoin.one"),
          twitter = listOf("https://twitter.com/Novacoin_NVC"),
          messageBoard = emptyList(),
          chat = listOf("https://discord.gg/6juXnsSkGa", "https://t.me/NovaCoin_EN"),
          facebook = emptyList(),
          explorer =
            listOf(
              "https://chainz.cryptoid.info/nvc/",
              "https://app.nansen.ai/token-god-mode?chain=bnb&tab=transactions&tokenAddress=0xbf84720097de111a80f46f9d077643967042841a",
              "https://explorer.nova-coin.org/",
            ),
          reddit = listOf("https://reddit.com/r/NovacoinCommunity/"),
          technicalDoc = listOf("https://github.com/novacoin-project/novacoin/wiki"),
          sourceCode = listOf("https://github.com/novacoin-project/novacoin"),
          announcement = listOf("https://bitcointalk.org/index.php?topic=5189560.0"),
        ),
      platform =
        TokenPlatform(
          id = 1839,
          name = "BNB",
          slug = "bnb",
          symbol = "BNB",
          tokenAddress = "0xbf84720097de111a80f46f9d077643967042841a",
        ),
      dateAdded = "2013-04-28T00:00:00.000Z",
      twitterUsername = "Novacoin_NVC",
      dateLaunched = "2013-02-05T00:00:00.000Z",
      selfReportedCirculatingSupply = 5106060.19,
      selfReportedTags = null,
      selfReportedMarketCap = 132392.07855834218,
      infiniteSupply = false,
    ),
    TokenInfo(
      id = 7,
      name = "Devcoin",
      symbol = "DVC",
      category = "coin",
      description =
        "Devcoin (DVC) is a cryptocurrency launched in 2011. Users are able to generate DVC through the process of mining. Devcoin has a current supply of 15,167,257,500. The last known price of Devcoin is 0.00002298 USD and is up 0.00 over the last 24 hours. More information can be found at https://www.devcoin.org/.",
      slug = "devcoin",
      logo = "https://s2.coinmarketcap.com/static/img/coins/64x64/7.png",
      subreddit = "devcoin",
      notice = "",
      tags = listOf("mineable"),
      tagNames = listOf("Mineable"),
      tagGroups = listOf("OTHERS"),
      urls =
        TokenUrls(
          website = listOf("https://www.devcoin.org/"),
          twitter = listOf("https://twitter.com/DevcoinDAO"),
          messageBoard = emptyList(),
          chat = listOf("https://t.me/Devcoins"),
          facebook = listOf("https://www.facebook.com/devcoin"),
          explorer = listOf("https://explorer.devcoin.org"),
          reddit = listOf("https://reddit.com/r/devcoin"),
          technicalDoc = listOf("https://www.devtome.com/devcoin"),
          sourceCode = listOf("https://github.com/devcoin/core"),
          announcement = listOf("https://bitcointalk.org/index.php?topic=233997.0"),
        ),
      platform = null,
      dateAdded = "2013-04-28T00:00:00.000Z",
      twitterUsername = "DevcoinDAO",
      dateLaunched = "2011-07-21T00:00:00.000Z",
      selfReportedCirculatingSupply = null,
      selfReportedTags =
        listOf(
          "SHA-256",
          "Philanthropy",
          "Content Creation",
          "Gaming",
          "DAO",
          "Software",
          "Sidechain",
          "Web3",
          "Token",
          "Bitcoin Ecosystem",
        ),
      selfReportedMarketCap = null,
      infiniteSupply = false,
    ),
    TokenInfo(
      id = 8,
      name = "Feathercoin",
      symbol = "FTC",
      category = "coin",
      description =
        "Feathercoin (FTC) is a cryptocurrency . Users are able to generate FTC through the process of mining. Feathercoin has a current supply of 336,000,000 with 236,600,238 in circulation. The last known price of Feathercoin is 0.00235699 USD and is down -0.14 over the last 24 hours. It is currently trading on 12 active market(s) with $16.37 traded over the last 24 hours. More information can be found at http://feathercoin.com.",
      slug = "feathercoin",
      logo = "https://s2.coinmarketcap.com/static/img/coins/64x64/8.png",
      subreddit = "FeatherCoin",
      notice = "",
      tags =
        listOf(
          "mineable",
          "pow",
          "neoscrypt",
          "medium-of-exchange",
          "collectibles-nfts",
          "payments",
        ),
      tagNames =
        listOf(
          "Mineable",
          "PoW",
          "NeoScrypt",
          "Medium of Exchange",
          "Collectibles & NFTs",
          "Payments",
        ),
      tagGroups = listOf("OTHERS", "ALGORITHM", "ALGORITHM", "INDUSTRY", "CATEGORY", "INDUSTRY"),
      urls =
        TokenUrls(
          website = listOf("http://feathercoin.com"),
          twitter = listOf("https://twitter.com/Feathercoin"),
          messageBoard = listOf("https://forum.feathercoin.com"),
          chat = listOf("https://telegram.me/feathercoinofficial"),
          facebook = emptyList(),
          explorer =
            listOf(
              "http://explorer.feathercoin.com/",
              "https://chainz.cryptoid.info/ftc/",
              "https://fsight.chain.tips/",
            ),
          reddit = listOf("https://reddit.com/r/FeatherCoin"),
          technicalDoc = listOf("https://feathercoin.com/about/"),
          sourceCode = listOf("https://github.com/FeatherCoin/Feathercoin"),
          announcement = listOf("https://bitcointalk.org/index.php?topic=178286.0"),
        ),
      platform = null,
      dateAdded = "2013-05-03T00:00:00.000Z",
      twitterUsername = "Feathercoin",
      dateLaunched = null,
      selfReportedCirculatingSupply = null,
      selfReportedTags = null,
      selfReportedMarketCap = null,
      infiniteSupply = false,
    ),
    TokenInfo(
      id = 9,
      name = "Mincoin",
      symbol = "MNC",
      category = "coin",
      description =
        "Mincoin (MNC) is a cryptocurrency . Users are able to generate MNC through the process of mining. Mincoin has a current supply of 6,228,916.8879491. The last known price of Mincoin is 0.07458228 USD and is up 0.00 over the last 24 hours. More information can be found at https://www.mincoin.us/.",
      slug = "mincoin",
      logo = "https://s2.coinmarketcap.com/static/img/coins/64x64/9.png",
      subreddit = "MinCoin",
      notice = "",
      tags = listOf("mineable", "pow", "scrypt"),
      tagNames = listOf("Mineable", "PoW", "Scrypt"),
      tagGroups = listOf("OTHERS", "ALGORITHM", "ALGORITHM"),
      urls =
        TokenUrls(
          website = listOf("https://www.mincoin.us/"),
          twitter = listOf("https://twitter.com/mincoinus"),
          messageBoard = listOf("https://www.mincoinforum.com"),
          chat = emptyList(),
          facebook = emptyList(),
          explorer = listOf("http://cryptoexplore.com", "https://www.mincoinexplorer.com/"),
          reddit = listOf("https://reddit.com/r/MinCoin"),
          technicalDoc =
            listOf(
              "https://github.com/mincoin/mincoin-whitepaper/blob/master/docs/mincoin-whitepaper.pdf"
            ),
          sourceCode = listOf("https://github.com/mincoin"),
          announcement = listOf("https://bitcointalk.org/index.php?topic=165397.0"),
        ),
      platform = null,
      dateAdded = "2013-05-03T00:00:00.000Z",
      twitterUsername = "mincoinus",
      dateLaunched = null,
      selfReportedCirculatingSupply = null,
      selfReportedTags = null,
      selfReportedMarketCap = null,
      infiniteSupply = false,
    ),
    TokenInfo(
      id = 10,
      name = "Freicoin",
      symbol = "FRC",
      category = "coin",
      description =
        "Freicoin (FRC) is a cryptocurrency . Users are able to generate FRC through the process of mining. Freicoin has a current supply of 100,000,000 with 0 in circulation. The last known price of Freicoin is 0.02234799 USD and is up 0.00 over the last 24 hours. It is currently trading on 1 active market(s) with $0.00 traded over the last 24 hours. More information can be found at http://freico.in.",
      slug = "freicoin",
      logo = "https://s2.coinmarketcap.com/static/img/coins/64x64/10.png",
      subreddit = "",
      notice = "",
      tags = listOf("mineable", "pow", "sha-256"),
      tagNames = listOf("Mineable", "PoW", "SHA-256"),
      tagGroups = listOf("OTHERS", "ALGORITHM", "ALGORITHM"),
      urls =
        TokenUrls(
          website = listOf("http://freico.in"),
          twitter = listOf("https://twitter.com/Freicoin"),
          messageBoard = listOf("https://freicoinalliance.com/"),
          chat = emptyList(),
          facebook = emptyList(),
          explorer = listOf("http://freicoin.info/chain/Freicoin"),
          reddit = emptyList(),
          technicalDoc = listOf("http://freico.in/docs/freimarkets.pdf"),
          sourceCode = listOf("https://github.com/freicoin/freicoin"),
          announcement = emptyList(),
        ),
      platform = null,
      dateAdded = "2013-05-03T00:00:00.000Z",
      twitterUsername = "Freicoin",
      dateLaunched = null,
      selfReportedCirculatingSupply = null,
      selfReportedTags = null,
      selfReportedMarketCap = null,
      infiniteSupply = false,
    ),
  )
